DROP TABLE customer_processed;

-- Q1. What is the total revenue generated by male vs. female customers?
describe customer_processed;
select * from customer_processed limit 5;

SELECT gender, SUM(purchase_amount) as revenue
FROM customer_processed
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount 
FROM customer_processed
WHERE discount_applied = "Yes" AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer_processed);

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating),2) AS avg_review
FROM customer_processed
GROUP BY item_purchased
ORDER BY item_purchased
DESC LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type, ROUND(AVG(purchase_amount),2) AS "Average by Shipping"
FROM customer_processed
WHERE shipping_type IN ("Standard", "Express")
GROUP By shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status from customer_processed LIMIT 100;

SELECT subscription_status, COUNT(*) AS 'Total Customer', 
		ROUND(AVG(Purchase_Amount), 2) AS avg_spent, ROUND(SUM(Purchase_Amount), 2) AS Total_Spent
FROM customer_processed
GROUP BY subscription_status
ORDER BY total_spent, Avg_spent DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased, 
ROUND(100 * SUM(
CASE 
	WHEN discount_applied='Yes'THEN 1 ELSE 0 END)/COUNT(*), 2) AS discount_percentage
FROM customer_processed 
GROUP BY item_purchased
ORDER BY discount_percentage DESC LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type AS
(
	SELECT customer_id, previous_purchases, 
    CASE
		WHEN previous_purchases=1 THEN "New"
        WHEN previous_purchases Between 2 AND 10 THEN 'Returning' 
        ELSE 'Loyal'
	END As customer_segment
FROM customer_processed
)

SELECT customer_segment, COUNT(*) 
FROM customer_type 
GROUP BY customer_segment;

-- Q8. What are the top 3 most purchased products within each category?
with item_counts AS
(
SELECT category, item_purchased, COUNT(customer_id) AS Total_Order, 
	row_number() OVER (partition by category order by count(customer_id) desc) as item_rank 
FROM customer_processed 
group by category, item_purchased
)

SELECT item_rank, category, item_purchased, total_order
FROM item_counts 
WHERE item_rank<=3
ORDER BY item_rank;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) AS repeat_buyers
FROM customer_processed
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group?
SELECT age_group, SUM(purchase_amount) AS rev_contribution
FROM customer_processed
GROUP BY age_group
ORDER BY rev_contribution DESC;